project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  cookie-consent: true
  title: "Xinzhuo Huang"
  google-analytics:
    tracking-id: "G-7HHBQV7LX3"
  favicon: icon.png
  site-url: https://xinzhuo.work
  description: "Xinzhuo's Personal Website"
  twitter-card: true
  open-graph: true
  navbar:
    logo: icon.png
    title: false
    right:
      - text: CV
        href: cv/index.html
      - text: BLOG
        href: blog/index.html
      - text: DATA
        href: data/index.html
      - text: PROJECT
        href: project/index.html
      - icon: rss
        href: blog/index.xml
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/xinzhuohkust/xinzhuo
          - text: Report a Bug
            url:  https://github.com/xinzhuohkust/xinzhuo/issues
  page-footer:
    border: false
    center: "Powered by [Quarto](https://quarto.org) | © 2023 [Xinzhuo Huang](/cv/)"  

format:
  html:
    theme:
      light: [flatly, scss/light.scss]
      dark: [darkly, scss/dark.scss]
    css: scss/styles.css
    code-link: true
    link-external-icon: false
    link-external-newwindow: true
    smooth-scroll: true
    highlight-style: gruvbox
    df-print: paged
    code-fold: true
    code-block-bg: "#f5f5f5"
    code-block-border-left: "#E0E0E0"
    toc: true
    toc-depth: 3
    toc-location: right
    link-citations: yes
    comments:
      giscus: 
        repo: xinzhuohkust/comments
        theme: light
      hypothesis: 
        theme: clean

editor: visual
